spring:
  datasource:
    url: jdbc:h2:mem:env:dev
    driver-class-name: org.h2.Driver
    username: SA_dev
    password:

custom:
  datasource:
    enabled: true
    url: jdbc:h2:mem:env:dev:custom

debug: false
