spring:
  datasource:
    url: jdbc:h2:mem:local
    driver-class-name: org.h2.Driver
    username: SA
    password:

custom:
  datasource:
    enabled: true
    url: jdbc:h2:mem:local:custom

debug: false

management:
  endpoints:
    web:
      exposure:
        include: 'health,appInfo'