spring:
  kafka:
    groupId: avro
    bootstrap:
      servers: ${KAFKA_HOST}:${KAFKA_PORT}
    producer:
      bootstrap:
        servers: ${KAFKA_HOST}:${KAFKA_PORT}
      retries: 0
    consumer:
      bootstrap:
        servers: ${KAFKA_HOST}:${KAFKA_PORT}

debug: false